[workspace]
members = [
	"programs/*",
	"sdk-rs"
]
exclude = [
	"deps/serum-dex"
]
resolver = "2"

[profile.release]
lto = "fat"
codegen-units = 1

[profile.release.build-override]
opt-level = 3
incremental = false
codegen-units = 1
